[package]
name = "opengl-rend"
version = "0.1.0"
edition = "2021"


[lints.clippy]
# unwrap_used = "deny"
# expect_used = "deny"
# panic = "deny"


[dependencies]
bitflags = "2.9.0"
gl = "0.14.0"
glam = "0.30.1"
glfw = "0.59.0"
thiserror = "2.0.12"
xml = "0.8.20"
